### ISSUE TITLE
rootdir/ files aren't being copied when building TWRP

### ISSUE THREAD

**Issue by TBM13** [Android4Lumia/android_device_nokia_fame#24]
Already set recovery variant to TWRP in BoardConfig and i also did make clean.

I'm not sure if all files are not being copied, but i know that twrp.fstab isn't.

**Comment by TBM13** [comment]
If i remember fine, when i tried to build LOS 14.1 last time, the kernel didn't booted so i had to use LOS 13.0 one. Maybe it happened the same than when i tried to build TWRP.

**Comment by feherneoh** [comment]
Cannot really tell what the reason might be without checking what changes the others did, as I wasn't involved in the LOS14.1 bringup, however I'm positive it worked in case of LOS13 last time I checked

**Comment by TBM13** [comment]
Update: I rebuilt TWRP, but this time i didn't have the problem. However, i have to set RECOVERY_VARIANT := twrp in the BoardConfig of the common tree, else LOS recovery will be built instead.

Issue closed.

**Comment by feherneoh** [comment]
When I build, I set RECOVERY_VARIANT in the environment variables, not in BoardConfig. This way the tree can be built without TWRP just fine, and when one NEEDS it, it can simply be enabled for one build.

**Comment by TBM13** [comment]
I didn't know i could do that. Thank you for telling me.
